service.port=8080

# Anthropic协议的模型
langchain4j.anthropic.chat-model.api-key = ${MINIMAX_API_KEY}
langchain4j.anthropic.chat-model.base-url = https://api.minimaxi.com/anthropic/v1
langchain4j.anthropic.chat-model.model-name = MiniMax-M2.7

# pinecone数据库apiKey
pine.cone.api.key = ${PINECONE_API_KEY}